steps:

  - id: "Running docker-compose"
    name: 'gcr.io/$PROJECT_ID/docker-compose:1.25.5'
    args: ['-f','docker-compose.yaml','up','-d']

  - id: "Running GO TEST"
    name: 'gcr.io/$PROJECT_ID/docker-compose:1.25.5'
    args: ['-f','docker-compose.yaml','run','calc','go','test','calculation.go','calculation_test.go','-v']
    
  - id: "Send image Google Container Registry"
    name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','gcr.io/$PROJECT_ID/go-hpa:$SHORT_SHA#g','./docker/.']

  - id: "Adjusting production k8s"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        sed 's#img-app-deployment#gcr.io/$PROJECT_ID/go-hpa:$SHORT_SHA#g' ./k8s/deployment.yaml > ./k8s/deployment.prod.yaml;
  
  - id: "Deploy Go - k8s deployment"
    name: "gcr.io/cloud-builders/kubectl"
    args:
      - 'apply'
      - '-f'
      - './k8s/deployment.prod.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'

  - id: "Deploy Go - k8s service"
    name: "gcr.io/cloud-builders/kubectl"
    args:
      - 'apply'
      - '-f'
      - './k8s/service.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'

  - id: "Deploy Go - k8s hpa"
    name: "gcr.io/cloud-builders/kubectl"
    args:
      - 'apply'
      - '-f'
      - './k8s/hpa.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'    

images:
  - 'gcr.io/$PROJECT_ID/go-hpa:$SHORT_SHA#g'